use_frameworks!

platform :ios, '10.0'

target 'ExhibitionInfoLib_Example' do
  pod 'ExhibitionInfoLib', :path => '../'

  target 'ExhibitionInfoLib_Tests' do
    inherit! :search_paths

    
  end
end
